### ISSUE TITLE
Retargetting Visual Studio Project

### ISSUE THREAD

**Issue by oaishi** [lyf7115/LayoutBlending#1]
Hi, my current window setup is incompatible with the given visual studio solution. Hence, I am trying to rebuild it from scratch. However, I am unable to trace the dependencies. Can you please tell me where I can find the Qt 5.9.1 release? 

Thanks again for sharing the code!

**Comment by lyf7115** [comment]
Hey, thanks for taking a look at our work.
You could try this link(https://download.qt.io/archive/qt/5.9/) to find Qt 5.9.1.
